name: chat_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  csc_picker:
    git:
      url: https://github.com/Harshit2756/csc_picker_more_options.git

  shimmer: ^3.0.0
  #. internationalization
  intl: ^0.19.0

  #. state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #. network
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  json_annotation: ^4.9.0

  #. permission handler
  permission_handler: ^11.3.1

  #. picker
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  cached_network_image: ^3.4.1

  #. utils
  logger: ^2.5.0
  device_info_plus: ^11.2.1
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
