// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwA9zl7HIF9L4DoYcyzvlPmQTJF6czMs',
    appId: '1:9058218109:web:08366ce0dc8a96cf0fc114',
    messagingSenderId: '9058218109',
    projectId: 'chat-app-1f160',
    authDomain: 'chat-app-1f160.firebaseapp.com',
    storageBucket: 'chat-app-1f160.firebasestorage.app',
    measurementId: 'G-X7NPV7GXCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYX3TdHkNF1gQ-oLztEZRnn8XiAdV1WdQ',
    appId: '1:9058218109:android:68649c477be415b70fc114',
    messagingSenderId: '9058218109',
    projectId: 'chat-app-1f160',
    storageBucket: 'chat-app-1f160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZoN-Lh0q5uU3mx9BQ7QcLuVOsmbRSJyo',
    appId: '1:9058218109:ios:4472c69ef7814fc60fc114',
    messagingSenderId: '9058218109',
    projectId: 'chat-app-1f160',
    storageBucket: 'chat-app-1f160.firebasestorage.app',
    androidClientId: '9058218109-nces52a28omvbb3o56a5beibo1oghn6p.apps.googleusercontent.com',
    iosClientId: '9058218109-t4o6vvs783mt770ggti8k0gcikv24v7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZoN-Lh0q5uU3mx9BQ7QcLuVOsmbRSJyo',
    appId: '1:9058218109:ios:4472c69ef7814fc60fc114',
    messagingSenderId: '9058218109',
    projectId: 'chat-app-1f160',
    storageBucket: 'chat-app-1f160.firebasestorage.app',
    androidClientId: '9058218109-nces52a28omvbb3o56a5beibo1oghn6p.apps.googleusercontent.com',
    iosClientId: '9058218109-t4o6vvs783mt770ggti8k0gcikv24v7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKwA9zl7HIF9L4DoYcyzvlPmQTJF6czMs',
    appId: '1:9058218109:web:2e05b85dc8bb46290fc114',
    messagingSenderId: '9058218109',
    projectId: 'chat-app-1f160',
    authDomain: 'chat-app-1f160.firebaseapp.com',
    storageBucket: 'chat-app-1f160.firebasestorage.app',
    measurementId: 'G-FLZ4585C0W',
  );

}